{% set name = "font-otf-fontawesome" %}
{% set version = "6.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FortAwesome/Font-Awesome/releases/download/{{ version }}/fontawesome-free-{{ version }}-desktop.zip
  sha256: 3118838d8d0aa88b8c9a5e132f8a195a3f1b23895ae66c61dc6746f9ceef80da

build:
  number: 0
  noarch: generic

requirements:
  build:
    - __unix

test:
  commands:
    - test -f "${PREFIX}/fonts/Font Awesome 6 Brands-Regular-400.otf"  # [unix]
    - test -f "${PREFIX}/fonts/Font Awesome 6 Free-Regular-400.otf"    # [unix]
    - test -f "${PREFIX}/fonts/Font Awesome 6 Free-Solid-900.otf"      # [unix]

about:
  home: https://fontawesome.com/
  summary: The iconic SVG, font, and CSS toolkit
  description: |
    Font Awesome is the Internet's icon library and toolkit, used by millions of designers, developers, and content creators.
  license: OFL-1.1
  license_file: LICENSE.txt
  dev_url: https://github.com/FortAwesome/Font-Awesome

extra:
  recipe-maintainers:
    - freundTech
